"""Capital flow sankey — daily $ → sector → ticker."""

from collections import defaultdict

from investment_journal.models.allocation import Allocation


def _short_sector(s: str) -> str:
    return s.split("/")[0].strip()


def render_capital_flow_sankey(allocation: Allocation) -> str:
    by_sector: dict[str, list] = defaultdict(list)
    for p in allocation.positions:
        by_sector[_short_sector(p.sector)].append(p)

    src = f"Daily ${allocation.dca.total_per_day_usd:g}"
    rows: list[str] = []
    for sec, ps in by_sector.items():
        rows.append(f"{src},{sec},{sum(p.dca_per_day_usd for p in ps):g}")
    for sec, ps in by_sector.items():
        for p in ps:
            rows.append(f"{sec},{p.ticker},{p.dca_per_day_usd:g}")
    sankey = "\n".join(rows)

    return f"""# Capital flow

_Auto-generated by `scripts/render_dashboards.py` from `portfolio/allocation.yml`. Do not edit by hand._

```mermaid
---
config:
  sankey:
    showValues: true
---
sankey-beta
{sankey}
```
"""
