"""Capital flow sankey — daily $ → sector → ticker."""

from collections import defaultdict
from datetime import date, timedelta

from investment_journal.models.allocation import Allocation
from investment_journal.models.dca_history import DCAHistory
from investment_journal.models.earnings_event import EarningsEvent


PNL_BLOCK_START = "<!-- pnl-start -->"
PNL_BLOCK_END = "<!-- pnl-end -->"


def _fmt_usd(x: float) -> str:
    return f"${x:,.2f}"


def _fmt_signed_usd(x: float) -> str:
    return ("+" if x >= 0 else "−") + f"${abs(x):,.2f}"


def _fmt_signed_pct(x: float) -> str:
    return ("+" if x >= 0 else "−") + f"{abs(x):,.2f}%"


def render_dca_pnl(history: DCAHistory, *, today: date) -> str:
    """Full DCA P&L dashboard at portfolio/dashboards/dca-pnl.md."""
    tickers = history.tickers()
    lines = [
        "# DCA P&L",
        "",
        "_Auto-generated by `scripts/record_dca_fills.py` from `portfolio/dca_history.json`. Do not edit by hand._",
        "",
        f"_Updated {today.isoformat()}._",
        "",
    ]
    if not tickers:
        lines += ["_No executed fills recorded yet._", ""]
        return "\n".join(lines)

    total_cb = 0.0
    total_mv = 0.0
    rows: list[str] = []
    for t in tickers:
        cb = history.cost_basis(t)
        sh = history.shares_held(t)
        m = history.marks.get(t)
        mark = m.price_usd if m else None
        mark_as_of = m.as_of.isoformat() if m else "—"
        if mark is None:
            mv_str = "—"
            pnl_abs_str = "—"
            pnl_pct_str = "—"
        else:
            mv = sh * mark
            pnl_abs = mv - cb
            pnl_pct = (mv / cb - 1.0) * 100.0 if cb else 0.0
            total_mv += mv
            total_cb += cb
            mv_str = _fmt_usd(mv)
            pnl_abs_str = _fmt_signed_usd(pnl_abs)
            pnl_pct_str = _fmt_signed_pct(pnl_pct)
        rows.append(
            f"| {t} | {history.fills_count(t)} | {_fmt_usd(cb)} | {sh:,.4f} | "
            f"{_fmt_usd(mark) if mark else '—'} | {mv_str} | {pnl_abs_str} | "
            f"{pnl_pct_str} | {mark_as_of} |"
        )

    lines += [
        "## Per ticker",
        "",
        "| Ticker | Fills | Cost basis | Shares | Mark | Market value | Unrealized P&L | % | Mark as of |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---|",
        *rows,
        "",
        "## Portfolio",
        "",
        f"- Cost basis: {_fmt_usd(total_cb)}",
        f"- Market value: {_fmt_usd(total_mv)}",
    ]
    if total_cb > 0:
        total_pnl = total_mv - total_cb
        total_pct = (total_mv / total_cb - 1.0) * 100.0
        lines.append(f"- Unrealized P&L: {_fmt_signed_usd(total_pnl)} ({_fmt_signed_pct(total_pct)})")
    lines.append("")

    return "\n".join(lines)


def render_dca_pnl_issue_block(
    history: DCAHistory,
    *,
    week_of: date,
    today: date,
) -> str:
    """Compact P&L block embedded in the weekly dca-tracker issue body.

    Wrapped in `<!-- pnl-start --> ... <!-- pnl-end -->` so the script can
    locate and replace it idempotently.
    """
    week_fills = history.fills_in_week(week_of)
    lines = [
        PNL_BLOCK_START,
        "",
        "**This week's fills**",
        "",
    ]
    if week_fills:
        lines += [
            "| Date | Ticker | Executed | Price | Shares |",
            "|---|---|---|---:|---:|",
        ]
        for f in week_fills:
            mark = "✓" if f.executed else "—"
            price = _fmt_usd(f.price_usd) if f.price_usd is not None else "—"
            shares = f"{f.shares:,.4f}" if f.shares is not None else "—"
            lines.append(f"| {f.on_date.isoformat()} | {f.ticker} | {mark} | {price} | {shares} |")
    else:
        lines.append("_No fills recorded for this week yet._")

    lines += ["", "**Cumulative P&L**", ""]
    tickers = history.tickers()
    if not tickers:
        lines.append("_No executed fills recorded yet._")
    else:
        total_cb = 0.0
        total_mv = 0.0
        priced = False
        for t in tickers:
            total_cb += history.cost_basis(t)
            m = history.marks.get(t)
            if m is not None:
                total_mv += history.market_value(t, m.price_usd)
                priced = True
        if priced and total_cb > 0:
            pnl = total_mv - total_cb
            pct = (total_mv / total_cb - 1.0) * 100.0
            lines.append(
                f"- Cost basis {_fmt_usd(total_cb)} → market value {_fmt_usd(total_mv)} = "
                f"{_fmt_signed_usd(pnl)} ({_fmt_signed_pct(pct)})"
            )
        else:
            lines.append(f"- Cost basis {_fmt_usd(total_cb)}; market value pending mark fetch.")
        lines.append("- Detail: [`portfolio/dashboards/dca-pnl.md`](../blob/main/portfolio/dashboards/dca-pnl.md)")

    lines += ["", f"_Updated {today.isoformat()}._", "", PNL_BLOCK_END]
    return "\n".join(lines)


def _short_sector(s: str) -> str:
    return s.split("/")[0].strip()


def _short_sector(s: str) -> str:
    return s.split("/")[0].strip()


def render_upcoming_earnings(
    events: list[tuple[EarningsEvent, int | None]],
    *,
    today: date,
    horizon_days: int = 90,
) -> str:
    """Sorted table of upcoming earnings within `horizon_days`.

    `events` is a list of (EarningsEvent, issue_number) pairs. Events outside
    the [today, today+horizon] window are dropped. Sort key: (date, ticker).
    """
    horizon_end = today + timedelta(days=horizon_days)
    upcoming = sorted(
        [(e, n) for e, n in events if today <= e.expected_date <= horizon_end],
        key=lambda pair: (pair[0].expected_date, pair[0].ticker),
    )

    lines = [
        "# Upcoming earnings",
        "",
        "_Auto-generated by `scripts/render_upcoming_earnings.py` from open `earnings` issues. Do not edit by hand._",
        "",
        f"_Window: {today.isoformat()} → {horizon_end.isoformat()} ({horizon_days} days). Updated {today.isoformat()}._",
        "",
    ]
    if not upcoming:
        lines += ["_None scheduled in this window._", ""]
        return "\n".join(lines)

    lines += [
        "| Date | Ticker | Quarter | Timing | Issue |",
        "|---|---|---|---|---|",
    ]
    for e, n in upcoming:
        timing = "—" if e.timing == "unknown" else e.timing
        ref = f"[#{n}](../../issues/{n})" if n else "—"
        lines.append(
            f"| {e.expected_date.isoformat()} | {e.ticker} | {e.quarter} | {timing} | {ref} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_capital_flow_sankey(allocation: Allocation) -> str:
    by_sector: dict[str, list] = defaultdict(list)
    for p in allocation.positions:
        by_sector[_short_sector(p.sector)].append(p)

    src = f"Daily ${allocation.dca.total_per_day_usd:g}"
    rows: list[str] = []
    for sec, ps in by_sector.items():
        rows.append(f"{src},{sec},{sum(p.dca_per_day_usd for p in ps):g}")
    for sec, ps in by_sector.items():
        for p in ps:
            rows.append(f"{sec},{p.ticker},{p.dca_per_day_usd:g}")
    sankey = "\n".join(rows)

    return f"""# Capital flow

_Auto-generated by `scripts/render_dashboards.py` from `portfolio/allocation.yml`. Do not edit by hand._

```mermaid
---
config:
  sankey:
    showValues: true
---
sankey-beta
{sankey}
```
"""
