#!/usr/bin/env python3
"""
Regenerate portfolio dashboards from allocation.yml.

Deterministic, no network. Updates:
  - portfolio/dashboards/allocation.md   (target pie)
  - portfolio/dashboards/dca-flow.md     (flowchart + sankey by sector)
  - portfolio/dashboards/upcoming-earnings.md  (placeholder, only if missing)
  - README.md                            (auto block between portfolio markers)

Usage:
    python scripts/render_dashboards.py
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "render_dashboards.py needs PyYAML. Install with: pip install pyyaml\n"
    )
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOCATION_PATH = REPO_ROOT / "portfolio" / "allocation.yml"
DASHBOARDS_DIR = REPO_ROOT / "portfolio" / "dashboards"
README_PATH = REPO_ROOT / "README.md"

PORTFOLIO_BLOCK_START = "<!-- portfolio-start -->"
PORTFOLIO_BLOCK_END = "<!-- portfolio-end -->"


def load_allocation() -> dict:
    with ALLOCATION_PATH.open() as f:
        return yaml.safe_load(f)


def replace_block(text: str, marker_start: str, marker_end: str, new_inner: str) -> str:
    pattern = re.compile(
        re.escape(marker_start) + r".*?" + re.escape(marker_end),
        re.DOTALL,
    )
    replacement = f"{marker_start}\n{new_inner.strip()}\n{marker_end}"
    if pattern.search(text):
        return pattern.sub(replacement, text)
    return text.rstrip() + f"\n\n{replacement}\n"


def short_sector(s: str) -> str:
    """First segment before '/'. Sankey nodes prefer short labels."""
    return s.split("/")[0].strip()


# ---------- renderers ----------

def render_allocation_md(allocation: dict) -> str:
    pie = "\n".join(
        f'    "{p["ticker"]}" : {p["target_pct"]}'
        for p in allocation["positions"]
    )
    return f"""# Allocation

_Auto-generated by `scripts/render_dashboards.py`. Do not edit by hand._

```mermaid
pie showData title Target allocation
{pie}
```
"""


def render_dca_flow_md(allocation: dict) -> str:
    total = allocation["dca"]["total_per_day_usd"]

    # Flowchart: total → 6 tickers
    flow_lines = [f'flowchart LR\n  A["Daily ${total}"]']
    for p in allocation["positions"]:
        flow_lines.append(
            f'  A --> {p["ticker"]}["{p["ticker"]} ${p["dca_per_day_usd"]}"]'
        )
    flow = "\n".join(flow_lines)

    # Sankey: total → sector → ticker
    by_sector: dict[str, list[dict]] = defaultdict(list)
    for p in allocation["positions"]:
        by_sector[short_sector(p["sector"])].append(p)

    src = f"Daily ${total}"
    sankey_rows: list[str] = []
    for sec, ps in by_sector.items():
        sec_total = sum(p["dca_per_day_usd"] for p in ps)
        sankey_rows.append(f"{src},{sec},{sec_total}")
    for sec, ps in by_sector.items():
        for p in ps:
            sankey_rows.append(f'{sec},{p["ticker"]},{p["dca_per_day_usd"]}')
    sankey = "\n".join(sankey_rows)

    return f"""# Capital flow

_Auto-generated by `scripts/render_dashboards.py`. Do not edit by hand._

## Daily split (flowchart)

```mermaid
{flow}
```

## Daily split (sankey, grouped by sector)

```mermaid
---
config:
  sankey:
    showValues: true
---
sankey-beta
{sankey}
```
"""


def render_upcoming_earnings_md_placeholder() -> str:
    return """# Upcoming earnings

_Populated by `.github/workflows/earnings-watcher.yml`. Until the first run, this is empty._

```mermaid
gantt
    title Upcoming earnings (placeholder)
    dateFormat YYYY-MM-DD
    section Pending
    Run earnings-watcher to populate :a1, 2026-04-26, 1d
```
"""


def render_readme_block(allocation: dict) -> str:
    today = date.today().isoformat()
    rows = "\n".join(
        f'| {p["ticker"]} | {p["name"]} | {p["target_pct"]:.0f}% | ${p["dca_per_day_usd"]} | {p["role"]} |'
        for p in allocation["positions"]
    )
    pie = "\n".join(
        f'    "{p["ticker"]}" : {p["target_pct"]}'
        for p in allocation["positions"]
    )
    return f"""_Last refreshed: {today}_

```mermaid
pie showData title Target allocation
{pie}
```

| Ticker | Name | Target | Daily DCA | Role |
|---|---|---|---|---|
{rows}

See [`portfolio/dashboards/allocation.md`](portfolio/dashboards/allocation.md) (pie) and [`portfolio/dashboards/dca-flow.md`](portfolio/dashboards/dca-flow.md) (flowchart + sankey)."""


# ---------- top-level ----------

def main() -> int:
    allocation = load_allocation()
    DASHBOARDS_DIR.mkdir(parents=True, exist_ok=True)

    (DASHBOARDS_DIR / "allocation.md").write_text(render_allocation_md(allocation))
    (DASHBOARDS_DIR / "dca-flow.md").write_text(render_dca_flow_md(allocation))

    upcoming_path = DASHBOARDS_DIR / "upcoming-earnings.md"
    if not upcoming_path.exists():
        upcoming_path.write_text(render_upcoming_earnings_md_placeholder())

    if README_PATH.exists():
        text = README_PATH.read_text()
        text = replace_block(
            text,
            PORTFOLIO_BLOCK_START,
            PORTFOLIO_BLOCK_END,
            render_readme_block(allocation),
        )
        README_PATH.write_text(text)

    print(f"Rendered. {len(allocation['positions'])} positions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
