#!/usr/bin/env python3
"""
Regenerate the sankey dashboard from allocation.yml.

Deterministic, no network. Writes:
  - portfolio/dashboards/dca-flow.md   (sankey: daily $ → sector → ticker)

Usage:
    python scripts/render_dashboards.py
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "render_dashboards.py needs PyYAML. Install with: pip install pyyaml\n"
    )
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOCATION_PATH = REPO_ROOT / "portfolio" / "allocation.yml"
DASHBOARDS_DIR = REPO_ROOT / "portfolio" / "dashboards"


def short_sector(s: str) -> str:
    """First segment before '/'. Sankey nodes prefer short labels."""
    return s.split("/")[0].strip()


def render_sankey(allocation: dict) -> str:
    total = allocation["dca"]["total_per_day_usd"]
    by_sector: dict[str, list[dict]] = defaultdict(list)
    for p in allocation["positions"]:
        by_sector[short_sector(p["sector"])].append(p)

    src = f"Daily ${total}"
    rows: list[str] = []
    for sec, ps in by_sector.items():
        rows.append(f"{src},{sec},{sum(p['dca_per_day_usd'] for p in ps)}")
    for sec, ps in by_sector.items():
        for p in ps:
            rows.append(f"{sec},{p['ticker']},{p['dca_per_day_usd']}")
    sankey = "\n".join(rows)

    return f"""# Capital flow

_Auto-generated by `scripts/render_dashboards.py`. Do not edit by hand._

```mermaid
---
config:
  sankey:
    showValues: true
---
sankey-beta
{sankey}
```
"""


def main() -> int:
    allocation = yaml.safe_load(ALLOCATION_PATH.read_text())
    DASHBOARDS_DIR.mkdir(parents=True, exist_ok=True)
    (DASHBOARDS_DIR / "dca-flow.md").write_text(render_sankey(allocation))
    print(f"Rendered sankey for {len(allocation['positions'])} positions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
